name: coverage

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  coverage:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up cargo cache
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: cargo-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            cargo-

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: '0.19.0'
          args: '-- --test-threads 1'

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v3.1.1
        with:
          token: ${{secrets.CODECOV_TOKEN}}
